slurm:
  gpus: 1                         # --gres=gpu:1
  mem_per_gpu: 32                 # --mem=32G  this RAM not GPU memory
  time: 600                       # --time=10:00:00 10 h = 600 min
  cpus_per_gpu: 6                 # -n 4 tasks / 1 GPU
  cpus_per_task: null             # (let SlurmConfig infer)
  one_task_per_node: false         # --ntasks-per-gpu=1
  exclude: null                   # comma‑separated nodes to exclude
  partition: "a100-gpu,l40-gpu"   # --partition
  setup:
    - source ~/.bashrc
    - echo "FFMPEG located at $(which ffmpeg)"
    - echo "$(ffmpeg -version)"
    - cd /work/users/t/i/tis/VidMuse
    - source .venv/bin/activate
  qos: "gpu_access"               # --qos